repositories {
    maven { url = "https://maven.shedaniel.me/" }
    mavenCentral()
}

configurations {
    shadowCommon
}

dependencies {
    compileOnly "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    testCompileOnly "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    compileOnly "me.shedaniel.cloth:cloth-config:${project.cloth_version}", {
        exclude module: 'fabric-api'
    }

    implementation 'com.electronwill.night-config:json:3.6.6'
    shadowCommon 'com.electronwill.night-config:json:3.6.6'

    testImplementation platform("org.junit:junit-bom:5.11.4")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

tasks.withType(Test).tap {
    configureEach {
        useJUnitPlatform()
    }
}

processResources {
    releaseChangelog()
}

loom {
    accessWidenerPath = file("src/main/resources/betterf3.accesswidener")
}

architectury {
    common(rootProject.platforms.split(","))
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
