name: Build BetterF3 (Manual)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build the Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v6

      - name: Setup Java 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :fabric:build --stacktrace

      - name: Setup Environment Variables
        run: |
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^minecraft_version >> $GITHUB_ENV
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^mod_version >> $GITHUB_ENV

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: BetterF3-${{ env.mod_version }}-mc${{ env.minecraft_version }}
          path: |
            fabric/build/libs/*.jar
            **/build/libs/*.jar